### ISSUE TITLE
Maybe a mistake in generate_tss function

### ISSUE THREAD

**Issue by JohnGenome** [anthony-aylward/tssenrich#1]
Hi Anthony, i follow the tss-enrichment question recently, and find the package you made very useful. The problem came when i read your code and the hg19.refFlat.txt.gz data. It seems that generate_tss() only take the fifth column as tss coordinate regardless of the strand. But for minus chain, the tss is in sixth column. Could you please check this promblem, 3q. 
                                                                                                                                                                                   Hao

**Comment by anthony-aylward** [comment]
You are right, thank you for your help finding this mistake! In version 1.3.0 I have corrected `generate_tss()` so that, for genes on the minus strand, it will take the TSS from the sixth column of the hg19 reFlat data.
