### ISSUE TITLE
Excluding chromosomes

### ISSUE THREAD

**Issue by Simso86** [anthony-aylward/tssenrich#2]
Hi Anthony.
I got some ATAC-seq data that I am currently analyzing. As part of the quality control I find your tool very useful to obtain a single TSS enrichment score. However, I would need to be able to run tssenrich on a subset of chromosomes in my bam files. Is it possible to exclude chromosomes when running tssenrich?

The reason for this is that the reference genome I have used for mapping my reads (GRCh38) contains many extra chromosomes for unlocalized and unplaced sequences (with the "_random" and "chrUn_" parts in their names), as well as chrM and chrEBV. I generally remove these chromosomes before downstream analyses. Also the reference included no ALT contigs.
I guess that tssenrich takes all of these chromosomes into consideration when calculating TSS enrichment score, right? I have done this for my unaltered bam files. The scores I got are around 4, which is "concerning" according to the ENCODE standards. However, because I include all the extra chromosomes described above (to which a big part of my reads are mapping) it may be no surprise that the scores are low.

So again, my question: **Is there a way to exclude chromosomes in this tool? If not, is that considered as a future addition?**

Best regards,
Simon Söderholm

**Comment by anthony-aylward** [comment]
Hi Simon, this is a very good question, thanks for bringing it up. Development of `tssenrich` is slow right now, but I am working on a solution.

**Comment by anthony-aylward** [comment]
I have uploaded a new version of `tssenrich` to PyPI (1.4.3). Now, by default only "proper" chromosomes (1-22, X, Y) are used for TSSE calculation. I have extended the `--genome` argument to accept a user-provided gzipped BED file as input, in case you wish to use your own gene coordinates or analyze data from another organism. For anyone who wishes to replicate the previous behavior of `tssenrich`, BED files including extra sequences can be found here: https://github.com/anthony-aylward/tssenrich/tree/master/tssenrich

@Simso86 , can you tell me if this solves your issue?

**Comment by Simso86** [comment]
Thank you for the quick release of the updates version of the tool.
However, after installing the new version and running the same command as previously:

`tssenrich sample.bam --genome hg38 --processes 8 --memory 4 > sample_score.txt`

I get the following error:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/simso02/anaconda2/envs/base_copy/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/simso02/anaconda2/envs/base_copy/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/simso02/anaconda2/envs/base_copy/lib/python3.6/site-packages/tssenrich/tssenrich.py", line 292, in tss_enrichment
    flank_distance=flank_distance, flank_size=flank_size)),
  File "/home/simso02/anaconda2/envs/base_copy/lib/python3.6/site-packages/tssenrich/tssenrich.py", line 135, in tss_flanks_bed_str
    '\t'.join(str(coord) for coord in flank) for flank in flanks
  File "/home/simso02/anaconda2/envs/base_copy/lib/python3.6/site-packages/tssenrich/tssenrich.py", line 135, in <genexpr>
    '\t'.join(str(coord) for coord in flank) for flank in flanks
  File "/home/simso02/anaconda2/envs/base_copy/lib/python3.6/site-packages/tssenrich/tssenrich.py", line 112, in generate_tss_flanks
    for chrom, pos in tss:
  File "/home/simso02/anaconda2/envs/base_copy/lib/python3.6/site-packages/tssenrich/tssenrich.py", line 90, in generate_tss
    chrom, tss_plus, tss_minus, _, _, strand, *_ = line.split()
ValueError: not enough values to unpack (expected at least 6, got 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/simso02/anaconda2/envs/base_copy/bin/tssenrich", line 10, in <module>
    sys.exit(main())
  File "/home/simso02/anaconda2/envs/base_copy/lib/python3.6/site-packages/tssenrich/tssenrich.py", line 349, in main
    args.bam
  File "/home/simso02/anaconda2/envs/base_copy/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/simso02/anaconda2/envs/base_copy/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
ValueError: not enough values to unpack (expected at least 6, got 0)
```

I seems there is some problems with the multi-processing of tssenrich, but I am not sure.

**Comment by anthony-aylward** [comment]
Sorry about that, I was a little neglectful in my unit testing. I think the promblem was improper formatting of the new included BED files, but I have uploaded a fixed version to PyPI (1.4.4)

**Comment by Simso86** [comment]
Thank you. Now it works! My TSS enrichment scores become a little bit higher. I just have some additional questions:
1. Does the tool exclude the mitochondrial chromosome?
2. If I would want to also remove duplicates and blacklisted regions in my bam files and then run tssenrich again, how would this affect the calculations in your tool?

**Comment by anthony-aylward** [comment]
1. Yes, mitochondrial regions are now excluded from the calculation by default. Should users wish to include them, they can supply their own gzipped BED file to the `--genome` argument.

2. a. In my own experience, duplicate reads had only small effects on TSSE values, but of course this depends on the qualities of the dataset. For my part, I always reported TSSE values from de-dupped data, but the ENCODE standard for this was never clear to me.

2. b. Removing blacklisted regions should have a minimal effect on the TSSE results, since by default the only regions considered in the calculation are the TSS's of genes, which AFAIK have minimal overlap with blacklisted regions.
